---

- name: "Gather facts"
  hosts: 192.168.1.50
  gather_facts: false
  connection: network_cli
  tasks:
    - name: Gathering cpu usage
      ios_command:
        commands:
          - 'show process cpu | in CPU' 
      register: results

    - name: Save var
      debug:
        var: results.stdout

   
       
      
      
      

      
      
