---

- name: "Gathering CPU %"
  hosts: 192.168.1.50
  gather_facts: false
  connection: network_cli
  tasks:
    - name: "play 1: Gathering cpu usage"
      ios_command:
        commands:
          - 'show process cpu | include CPU' 
      register: results

    - name: "play 2: show results on the console"
      debug:
        msg: "{{ results.stdout[0] }}"

    - name: "play 3: create a directory output"
      ansible.builtin.file:
        path: "outputs"
        state: directory
      run_once: true

    - name: "play 4: copy content to a file"
      ansible.builtin.copy:
        content: "{{ results.stdout[0] }}\n"
        dest: "outputs/{{ inventory_hostname }}.txt"

        
        
      




   
       
      
      
      

      
      
